export const ACCENT_COLORS = [
  '#E5162E',
  '#555454',
];

export const possibleLetterPairSymbols = [
  'O',
  'V',
  'E',
  'R',
  'L',
  'A',
  'P',
];

export const possibleLetterStringSymbols = [
  {
    symbol: 'O',
    italic: true,
    vertical: false,
    bold: true,
  },
  {
    symbol: 'O',
    italic: true,
    vertical: false,
    bold: false,
  },
  {
    symbol: 'O',
    italic: false,
    vertical: false,
    bold: true,
  },
  {
    symbol: 'O',
    italic: false,
    vertical: false,
    bold: false,
  },
  {
    symbol: '$',
    italic: false,
    vertical: false,
    bold: false,
  },
  {
    symbol: '3',
    italic: false,
    vertical: false,
    bold: false,
  },
  {
    symbol: '4',
    italic: false,
    vertical: false,
    bold: false,
  },
  {
    symbol: '~',
    italic: false,
    vertical: false,
    bold: false,
  },
  {
    symbol: '^',
    italic: false,
    vertical: true,
    bold: false,
  },
  {
    symbol: '+',
    italic: false,
    vertical: false,
    bold: false,
  },
  {
    symbol: '#',
    italic: false,
    vertical: false,
    bold: false,
  },
  {
    symbol: '}',
    italic: false,
    vertical: false,
    bold: false,
    letterSpacing: '-0.4ch',
  },
  {
    symbol: ']',
    italic: false,
    vertical: false,
    bold: false,
    letterSpacing: '0',
  },
  {
    symbol: ')',
    italic: false,
    vertical: false,
    bold: true,
    letterSpacing: '0',
  },
  {
    symbol: 'R',
    italic: true,
    vertical: true,
    bold: false,
  },
  {
    symbol: '3',
    italic: false,
    vertical: true,
    bold: false,
    lineHeight: 0.34,
  },
  {
    symbol: '4',
    italic: false,
    vertical: true,
    bold: false,
  },
  {
    symbol: '+',
    italic: false,
    vertical: true,
    bold: false,
  },
  {
    symbol: '+++',
    italic: false,
    vertical: true,
    bold: false,
  },
  {
    symbol: '#',
    italic: false,
    vertical: true,
    bold: false,
    lineHeight: 0.35,
  },
  {
    symbol: '~~',
    italic: false,
    vertical: true,
    bold: false,
    lineHeight: 0.1,
  },
  {
    symbol: '^^',
    italic: false,
    vertical: true,
    bold: false,
    lineHeight: 0.25,
  },
  {
    symbol: '^',
    italic: false,
    vertical: true,
    bold: false,
    lineHeight: 0.25,
  },
  {
    symbol: '$$$$$$',
    italic: false,
    vertical: true,
    bold: false,
    lineHeight: 0.34,
    letterSpacing: '-0.2ch',
  },
  {
    symbol: 'O',
    italic: false,
    vertical: true,
    bold: false,
  },
];
